INSERT INTO `doctype_details`(`doctype_id`, `name`,  `type`,  `mandatory`, `value`) VALUES 
(1, 'Memo Journal','checkbox','1','["checked",""]'),
(1, 'Petty Cash Voucher','checkbox','1','["checked",""]'),
(1, 'Kwitansi','checkbox','1','["checked",""]'),
(1, 'Transmital Memo','checkbox','1','["checked",""]'),
(1, 'Memo Dinas POH','checkbox','1','["checked",""]'),
(2, 'Form Release Budget','checkbox','1','["checked",""]'),
(2, 'Form RFP','checkbox','1','["checked",""]'),
(2, 'Bukti Pembayaran','checkbox','1','["checked",""]'),
(2, 'Faktur Pajak','checkbox','1','["checked",""]'),
(2, 'Proposal','checkbox','1','["checked",""]'),
(2, 'No CO, SO','checkbox','1','["checked",""]'),
(2, 'Bukti Dokumentasi','checkbox','1','["checked",""]'),
(2, 'Transmital Memo','checkbox','1','["checked",""]'),
(2, 'Memo Dinas POH','checkbox','1','["checked",""]'),
(3, 'Form PPD','checkbox','1','["checked",""]'),
(3, 'Form SPPD','checkbox','1','["checked",""]'),
(3, 'No Dok Parking','checkbox','1','["checked",""]'),
(3, 'Undangan','checkbox','1','["checked",""]'),
(3, 'Bukti Pembayaran Transport','checkbox','1','["checked",""]'),
(3, 'Transmital Memo','checkbox','1','["checked",""]'),
(3, 'Memo Dinas POH','checkbox','1','["checked",""]'),
(4, 'Kategori','radio','1','["CAPEX","OPEX"]'),
(4, 'Lampiran Kartu Asset (Dilengkapi Jika CAPEX)','checkbox','1','["checked",""]'),
(4, 'Lampiran Jurnal MIGO','checkbox','1','["checked",""]'),
(4, 'Nilai Invoice','radio','1','["< 500 Jt", "> 500Jt"]'),
(4, 'Lembar Sirkuler Tanda Tangan (Dilengkapi Jika Nilai > 500jt)','checkbox','1','["checked",""]'),
(4, 'Object Pajak','radio','1','["PKP","Non PKP"]'),
(4, 'Invoice','checkbox','1','["checked",""]'),
(4, 'Faktur Pajak','checkbox','1','["checked",""]'),
(4, 'PKS','checkbox','1','["checked",""]'),
(4, 'Adendum PKS','checkbox','0','["checked",""]'),
(4, 'Transmital Memo','checkbox','1','["checked",""]'),
(4, 'Memo Dinas POH','checkbox','0','["checked",""]'),
(5, 'Kategori','radio','1','["CAPEX","OPEX"]'),
(5, 'Lampiran Kartu Asset (Dilengkapi Jika CAPEX)','checkbox','1','["checked",""]'),
(5, 'Lampiran Jurnal MIGO','checkbox','1','["checked",""]'),
(5, 'Nilai Invoice','radio','1','["< 500 Jt", "> 500Jt"]'),
(5, 'Lembar Sirkuler Tanda Tangan (Dilengkapi Jika Nilai > 500jt)','checkbox','1','["checked",""]'),
(5, 'Object Pajak','radio','1','["PKP","Non PKP"]'),
(5, 'Invoice','checkbox','1','["checked",""]'),
(5, 'Faktur Pajak','checkbox','1','["checked",""]'),
(5, 'PKS/SPMP','checkbox','1','["checked",""]'),
(5, 'Adendum PKS','checkbox','0','["checked",""]'),
(5, 'Berita Acara Pelaksanaan Pekerjaan (BAPP)','checkbox','1','["checked",""]'),
(5, 'Berita Acara Serah Terima (BAST)','checkbox','1','["checked",""]'),
(5, 'Berita Acara Serah Terima (BAST) dari OPS (Khusus Jasnaker)','checkbox','1','["checked",""]'),
(5, 'BA Rekon','checkbox','0','["checked",""]'),
(5, 'Working Order (WO)','checkbox','0','["checked",""]'),
(5, 'Delivery Order (DO) / Surat Jalan','checkbox','0','["checked",""]'),
(5, 'Lain-lain','checkbox','0','["checked",""]'),
(5, 'Lain-lain 2','checkbox','0','["checked",""]'),
(5, 'Lain-lain 3','checkbox','0','["checked",""]'),
(5, 'Lain-lain 4','checkbox','0','["checked",""]'),
(5, 'Lain-lain 5','checkbox','0','["checked",""]'),
(6, 'Kategori','radio','1','["CAPEX","OPEX"]'),
(6, 'Lampiran Kartu Asset (Dilengkapi Jika CAPEX)','checkbox','1','["checked",""]'),
(6, 'Lampiran Jurnal MIGO','checkbox','1','["checked",""]'),
(6, 'Nilai Invoice','radio','1','["< 500 Jt", "> 500Jt"]'),
(6, 'Lembar Sirkuler Tanda Tangan (Dilengkapi Jika Nilai > 500jt)','checkbox','1','["checked",""]'),
(6, 'Object Pajak','radio','1','["PKP","Non PKP"]'),
(6, 'Invoice','checkbox','1','["checked",""]'),
(6, 'Faktur Pajak','checkbox','1','["checked",""]'),
(6, 'PKS/SPMP','checkbox','1','["checked",""]'),
(6, 'Adendum PKS','checkbox','0','["checked",""]'),
(6, 'Berita Acara Pelaksanaan Pekerjaan (BAPP)','checkbox','0','["checked",""]'),
(6, 'Berita Acara Serah Terima (BAST)','checkbox','1','["checked",""]'),
(6, 'BA Rekon','checkbox','0','["checked",""]'),
(6, 'Working Order (WO)','checkbox','0','["checked",""]'),
(6, 'Delivery Order (DO) / Surat Jalan','checkbox','0','["checked",""]'),
(6, 'Bukti Dokumentasi (Foto dan Daftar Hadir)','checkbox','0','["checked",""]'),
(6, 'Bukti Transaportasi (Ticket Transportasi)','checkbox','0','["checked",""]'),
(6, 'Bukti Akomodasi (Rooming List, Ticket Hotel)','checkbox','0','["checked",""]'),
(6, 'Garansi Barang','checkbox','0','["checked",""]'),
(6, 'Lain-lain','checkbox','0','["checked",""]'),
(6, 'Lain-lain 2','checkbox','0','["checked",""]'),
(6, 'Lain-lain 3','checkbox','0','["checked",""]'),
(6, 'Lain-lain 4','checkbox','0','["checked",""]'),
(6, 'Lain-lain 5','checkbox','0','["checked",""]')
;